### PR TITLE
Use kotlin+buildSrc to manage dependencies

### PR DESCRIPTION
**Pull request by jmfayard**
more kotlin, better IDE integration

image

### CODE REVIEW

**Comment by MarcinMoskala** [comment]
I see value in strings extraction, but in the same time I see problem in having mixed Groovy-Kotlin Gradle configuration. It would make sense if all Gradle configurations would be moved to Kotlin

**Comment by jmfayard** [comment]
> It would make sense if all Gradle configurations would be moved to Kotlin

yes, that would be an interesting experiment
I don't have time right now to do that, but I would like to try someday

> I see value in strings extraction, but in the same time I see problem in having mixed Groovy-Kotlin Gradle configuration. 

I would ask: problem for who?
Not for gradle, it offers a java api and does not care wether you configure it with java or groovy or kotlin or a mix.
Not for the developer. If is interested by this project, we can assume he knows kotlin. The buildSrc+kotlin solution is super focused on a well known pain point around managing dependencies, the IDE integration makes it a superior alternative. Nothing else changes.

**Comment by jmfayard** [comment]
@MarcinMoskala 
Are you still interested in having all gradle configuration files migrated to Kotlin?
I would like to give it a try to see how that goes.

**Comment by jmfayard** [comment]
I will submit a better pull request

**Pull request closed without merging**
